-- MySQL Script generated by MySQL Workbench
-- dim. 29 mars 2020 16:51:42 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema offdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema offdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `offdb` DEFAULT CHARACTER SET utf8 ;
USE `offdb` ;

-- -----------------------------------------------------
-- Table `offdb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`category` (
  `idcategory` INT(15) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `offdb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`products` (
  `idproducts` INT(15) NOT NULL AUTO_INCREMENT,
  `brands` VARCHAR(300) NOT NULL,
  `code` BIGINT(30) NULL,
  `ingredients_text_fr` VARCHAR(3000) NULL,
  `nutrition_grade_fr` CHAR(1) NOT NULL COMMENT 'in the description we find nutriscore or nutriscore_grade',
  `product_name_fr` VARCHAR(300) NOT NULL,
  `quantity` VARCHAR(300) NULL, 
  `stores` VARCHAR(300) NULL,
  `url` VARCHAR(300) NOT NULL, 
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offdb`.`substitute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`substitute` (
  `idsubstitute` INT(15) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `brand` VARCHAR(300) NOT NULL,
  `code` BIGINT(20) NOT NULL,
  `nutriscore` CHAR(1) NOT NULL,
  `ingredients` VARCHAR(3000) NULL,
  `stores` VARCHAR(200) NULL,
  `url` VARCHAR(3000) NOT NULL,
  PRIMARY KEY (`idsubstitute`))
ENGINE = InnoDB
COMMENT = 'table of substitute product ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
